/**
 * Rainbow admin portal
 * # Rainbow administrator portal API guide  ## Preamble  ### Introduction  This guide describes list of API services that are provided by OT Rainbow management portal system. Services are used to manage OT Rainbow system entities  ### Protocol  REST interface is used for sending/receiving OT rainbow API messages. HTTP requests GET, DELETE, POST, UPDATE are used. Standard HTTP responses are used to provide requested information or error status. There is no session notion in OT Rainbow system, so requests could be issued according stateless model, without transport conservation between them. Additional data could be provided in message body. JSON is used as a main format for data encoding in message body part. Each request is started with the following pattern /{module}/{version}/ where {module} is a portal module name to address and {version} is a version of used API, par example, “v1.0”.  ### Security considerations  Each request should contain some credential information to authenticate itself. Standard HTTP authentication with basic/bearer modes is used. JSON Web Token mechanism is used to provide authentication information. JWT has a expire timeout that is controlled by OT Rainbow portal to prevent very long token usage. Also authentication with application token is used. The token must be provided in the request HTTP header, using a custom header: APIKey. At server side, token is verified, and if it doesn’t match, 403 Not Allowed response is sent. TLS is used as a transport protocol to support message exchanges between OT Rainbow portal and an application.  
 *
 * OpenAPI spec version: 1.82.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NotificationsIM', 'model/NotificationsIMBot', 'model/NotificationsIMBotSuccess', 'model/NotificationsIMSuccess'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/NotificationsIM'), require('../model/NotificationsIMBot'), require('../model/NotificationsIMBotSuccess'), require('../model/NotificationsIMSuccess'));
  } else {
    // Browser globals (root is window)
    if (!root.RainbowAdminPortal) {
      root.RainbowAdminPortal = {};
    }
    root.RainbowAdminPortal.NotificationsImApi = factory(root.RainbowAdminPortal.ApiClient, root.RainbowAdminPortal.NotificationsIM, root.RainbowAdminPortal.NotificationsIMBot, root.RainbowAdminPortal.NotificationsIMBotSuccess, root.RainbowAdminPortal.NotificationsIMSuccess);
  }
}(this, function(ApiClient, NotificationsIM, NotificationsIMBot, NotificationsIMBotSuccess, NotificationsIMSuccess) {
  'use strict';

  /**
   * NotificationsIm service.
   * @module api/NotificationsImApi
   * @version 1.82.0
   */

  /**
   * Constructs a new NotificationsImApi. 
   * @alias module:api/NotificationsImApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Send an IM to a Rainbow user
     * This API allows superadmin to send an instant message (IM) from a Rainbow user (who can be himself) to another Rainbow user.
     * @param {module:model/NotificationsIM} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/NotificationsIMSuccess} and HTTP response
     */
    this.notificationsIMWithHttpInfo = function(body) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling notificationsIM");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = NotificationsIMSuccess;
      return this.apiClient.callApi(
        '/api/rainbow/admin/v1.0/notifications/im', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Send an IM to a Rainbow user
     * This API allows superadmin to send an instant message (IM) from a Rainbow user (who can be himself) to another Rainbow user.
     * @param {module:model/NotificationsIM} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/NotificationsIMSuccess}
     */
    this.notificationsIM = function(body) {
      return this.notificationsIMWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Send an IM to a Rainbow user from a bot
     * This API allows superadmin to send an instant message (IM) from a Rainbow bot to another Rainbow user.
     * @param {module:model/NotificationsIMBot} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/NotificationsIMBotSuccess} and HTTP response
     */
    this.notificationsIMBotWithHttpInfo = function(body) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling notificationsIMBot");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = NotificationsIMBotSuccess;
      return this.apiClient.callApi(
        '/api/rainbow/admin/v1.0/notifications/im/bot', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Send an IM to a Rainbow user from a bot
     * This API allows superadmin to send an instant message (IM) from a Rainbow bot to another Rainbow user.
     * @param {module:model/NotificationsIMBot} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/NotificationsIMBotSuccess}
     */
    this.notificationsIMBot = function(body) {
      return this.notificationsIMBotWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
