/**
 * Rainbow admin portal
 * # Rainbow administrator portal API guide  ## Preamble  ### Introduction  This guide describes list of API services that are provided by OT Rainbow management portal system. Services are used to manage OT Rainbow system entities  ### Protocol  REST interface is used for sending/receiving OT rainbow API messages. HTTP requests GET, DELETE, POST, UPDATE are used. Standard HTTP responses are used to provide requested information or error status. There is no session notion in OT Rainbow system, so requests could be issued according stateless model, without transport conservation between them. Additional data could be provided in message body. JSON is used as a main format for data encoding in message body part. Each request is started with the following pattern /{module}/{version}/ where {module} is a portal module name to address and {version} is a version of used API, par example, “v1.0”.  ### Security considerations  Each request should contain some credential information to authenticate itself. Standard HTTP authentication with basic/bearer modes is used. JSON Web Token mechanism is used to provide authentication information. JWT has a expire timeout that is controlled by OT Rainbow portal to prevent very long token usage. Also authentication with application token is used. The token must be provided in the request HTTP header, using a custom header: APIKey. At server side, token is verified, and if it doesn’t match, 403 Not Allowed response is sent. TLS is used as a transport protocol to support message exchanges between OT Rainbow portal and an application.  
 *
 * The version of the OpenAPI document: 1.82.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.1.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetApiRainbowAdminV10RoomsSuccess'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GetApiRainbowAdminV10RoomsSuccess'));
  } else {
    // Browser globals (root is window)
    if (!root.RainbowAdminPortal) {
      root.RainbowAdminPortal = {};
    }
    root.RainbowAdminPortal.RoomsApi = factory(root.RainbowAdminPortal.ApiClient, root.RainbowAdminPortal.GetApiRainbowAdminV10RoomsSuccess);
  }
}(this, function(ApiClient, GetApiRainbowAdminV10RoomsSuccess) {
  'use strict';

  /**
   * Rooms service.
   * @module api/RoomsApi
   * @version 1.82.0
   */

  /**
   * Constructs a new RoomsApi. 
   * @alias module:api/RoomsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get all rooms id
     * Display a list of short room description including: **id** - room identifier, **name** - room name   
     * @param {String} accept application/json
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Allow to specify the number of rooms to retrieve.
     * @param {Number} opts.offset Allow to specify the position of first room to retrieve (first room if not specified). Warning: if offset > total, no results are returned.
     * @param {String} opts.sortField Sort room list based on the given field.
     * @param {Number} opts.sortOrder Specify order when sorting company list.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetApiRainbowAdminV10RoomsSuccess} and HTTP response
     */
    this.getApiRainbowAdminV10RoomsWithHttpInfo = function(accept, opts) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'accept' is set
      if (accept === undefined || accept === null) {
        throw new Error("Missing the required parameter 'accept' when calling getApiRainbowAdminV10Rooms");
      }

      var pathParams = {
      };
      var queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sortField': opts['sortField'],
        'sortOrder': opts['sortOrder'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'accept': accept
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = GetApiRainbowAdminV10RoomsSuccess;
      return this.apiClient.callApi(
        '/api/rainbow/admin/v1.0/rooms', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get all rooms id
     * Display a list of short room description including: **id** - room identifier, **name** - room name   
     * @param {String} accept application/json
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Allow to specify the number of rooms to retrieve.
     * @param {Number} opts.offset Allow to specify the position of first room to retrieve (first room if not specified). Warning: if offset > total, no results are returned.
     * @param {String} opts.sortField Sort room list based on the given field.
     * @param {Number} opts.sortOrder Specify order when sorting company list.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetApiRainbowAdminV10RoomsSuccess}
     */
    this.getApiRainbowAdminV10Rooms = function(accept, opts) {
      return this.getApiRainbowAdminV10RoomsWithHttpInfo(accept, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
