/**
 * Rainbow Enduser portal
 * # Rainbow end user portal API guide  ## Preamble  ### Introduction  This guide describes list of API services that are provided by OT Rainbow End user portal. This portal is dedicated to end user features.  ### Protocol  REST interface is used for sending/receiving OT rainbow API messages. HTTP requests GET, DELETE, POST, UPDATE are used. Standard HTTP responses are used to provide requested information or error status. There is no session notion in OT Rainbow system, so requests could be issued according stateless model, without transport conservation between them. Additional data could be provided in message body. JSON is used as a main format for data encoding in message body part. Each request is started with the following pattern /{module}/{version}/ where {module} is a portal module name to address and {version} is a version of used API, par example, “v1.0”.  ### Security considerations  Each request should contain some credential information to authenticate itself. Standard HTTP authentication with basic/bearer modes is used. JSON Web Token mechanism is used to provide authentication information. JWT has a expire timeout that is controlled by OT Rainbow portal to prevent very long token usage. Also authentication with application token is used. The token must be provided in the request HTTP header, using a custom header: APIKey. At server side, token is verified, and if it doesn’t match, 403 Not Allowed response is sent. TLS is used as a transport protocol to support message exchanges between OT Rainbow portal and an application.  
 *
 * OpenAPI spec version: 1.84.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CancelJoinCompanyRequestSuccessDataRequestedToCompanyAdmin'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CancelJoinCompanyRequestSuccessDataRequestedToCompanyAdmin'));
  } else {
    // Browser globals (root is window)
    if (!root.RainbowEnduserPortal) {
      root.RainbowEnduserPortal = {};
    }
    root.RainbowEnduserPortal.CancelJoinCompanyRequestSuccessData = factory(root.RainbowEnduserPortal.ApiClient, root.RainbowEnduserPortal.CancelJoinCompanyRequestSuccessDataRequestedToCompanyAdmin);
  }
}(this, function(ApiClient, CancelJoinCompanyRequestSuccessDataRequestedToCompanyAdmin) {
  'use strict';



  /**
   * The CancelJoinCompanyRequestSuccessData model module.
   * @module model/CancelJoinCompanyRequestSuccessData
   * @version 1.84.0
   */

  /**
   * Constructs a new <code>CancelJoinCompanyRequestSuccessData</code>.
   * @alias module:model/CancelJoinCompanyRequestSuccessData
   * @class
   * @param requestedCompanyId {String} Unique Id of the company the requesting user wants to join
   * @param requestingUserId {String} Requesting user unique Rainbow Id
   * @param requestingUserLoginEmail {String} Requesting user email
   * @param requestingDate {Date} Date the request was created
   * @param requestedCompanyInvitationId {String} If the request was sent using a JoinCompanyInvite id, this field is set with this Id
   * @param requestedCompanyName {String} Name of the company the requesting user wants to join
   * @param requestedNotificationLanguage {String} Requested notification language to use if language of company admin is not defined (used to re-send email request in that language)
   * @param id {String} Join company request unique Id
   * @param lastNotificationDate {Date} Date when the last email notification was sent
   * @param status {String} Request status: one of `pending`, `accepted`, `declined`, `canceled`
   */
  var exports = function(requestedCompanyId, requestingUserId, requestingUserLoginEmail, requestingDate, requestedCompanyInvitationId, requestedCompanyName, requestedNotificationLanguage, id, lastNotificationDate, status) {
    var _this = this;

    _this['requestedCompanyId'] = requestedCompanyId;
    _this['requestingUserId'] = requestingUserId;
    _this['requestingUserLoginEmail'] = requestingUserLoginEmail;
    _this['requestingDate'] = requestingDate;
    _this['requestedCompanyInvitationId'] = requestedCompanyInvitationId;
    _this['requestedCompanyName'] = requestedCompanyName;
    _this['requestedNotificationLanguage'] = requestedNotificationLanguage;
    _this['id'] = id;
    _this['lastNotificationDate'] = lastNotificationDate;
    _this['status'] = status;
  };

  /**
   * Constructs a <code>CancelJoinCompanyRequestSuccessData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CancelJoinCompanyRequestSuccessData} obj Optional instance to populate.
   * @return {module:model/CancelJoinCompanyRequestSuccessData} The populated <code>CancelJoinCompanyRequestSuccessData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('requestedCompanyId')) {
        obj['requestedCompanyId'] = ApiClient.convertToType(data['requestedCompanyId'], 'String');
      }
      if (data.hasOwnProperty('requestingUserId')) {
        obj['requestingUserId'] = ApiClient.convertToType(data['requestingUserId'], 'String');
      }
      if (data.hasOwnProperty('requestingUserLoginEmail')) {
        obj['requestingUserLoginEmail'] = ApiClient.convertToType(data['requestingUserLoginEmail'], 'String');
      }
      if (data.hasOwnProperty('requestingDate')) {
        obj['requestingDate'] = ApiClient.convertToType(data['requestingDate'], 'Date');
      }
      if (data.hasOwnProperty('requestedCompanyInvitationId')) {
        obj['requestedCompanyInvitationId'] = ApiClient.convertToType(data['requestedCompanyInvitationId'], 'String');
      }
      if (data.hasOwnProperty('requestedCompanyName')) {
        obj['requestedCompanyName'] = ApiClient.convertToType(data['requestedCompanyName'], 'String');
      }
      if (data.hasOwnProperty('requestedNotificationLanguage')) {
        obj['requestedNotificationLanguage'] = ApiClient.convertToType(data['requestedNotificationLanguage'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('requestedToCompanyAdmin')) {
        obj['requestedToCompanyAdmin'] = CancelJoinCompanyRequestSuccessDataRequestedToCompanyAdmin.constructFromObject(data['requestedToCompanyAdmin']);
      }
      if (data.hasOwnProperty('lastNotificationDate')) {
        obj['lastNotificationDate'] = ApiClient.convertToType(data['lastNotificationDate'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique Id of the company the requesting user wants to join
   * @member {String} requestedCompanyId
   */
  exports.prototype['requestedCompanyId'] = undefined;
  /**
   * Requesting user unique Rainbow Id
   * @member {String} requestingUserId
   */
  exports.prototype['requestingUserId'] = undefined;
  /**
   * Requesting user email
   * @member {String} requestingUserLoginEmail
   */
  exports.prototype['requestingUserLoginEmail'] = undefined;
  /**
   * Date the request was created
   * @member {Date} requestingDate
   */
  exports.prototype['requestingDate'] = undefined;
  /**
   * If the request was sent using a JoinCompanyInvite id, this field is set with this Id
   * @member {String} requestedCompanyInvitationId
   */
  exports.prototype['requestedCompanyInvitationId'] = undefined;
  /**
   * Name of the company the requesting user wants to join
   * @member {String} requestedCompanyName
   */
  exports.prototype['requestedCompanyName'] = undefined;
  /**
   * Requested notification language to use if language of company admin is not defined (used to re-send email request in that language)
   * @member {String} requestedNotificationLanguage
   */
  exports.prototype['requestedNotificationLanguage'] = undefined;
  /**
   * Join company request unique Id
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/CancelJoinCompanyRequestSuccessDataRequestedToCompanyAdmin} requestedToCompanyAdmin
   */
  exports.prototype['requestedToCompanyAdmin'] = undefined;
  /**
   * Date when the last email notification was sent
   * @member {Date} lastNotificationDate
   */
  exports.prototype['lastNotificationDate'] = undefined;
  /**
   * Request status: one of `pending`, `accepted`, `declined`, `canceled`
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


