/**
 * Rainbow Enduser portal
 * # Rainbow end user portal API guide  ## Preamble  ### Introduction  This guide describes list of API services that are provided by OT Rainbow End user portal. This portal is dedicated to end user features.  ### Protocol  REST interface is used for sending/receiving OT rainbow API messages. HTTP requests GET, DELETE, POST, UPDATE are used. Standard HTTP responses are used to provide requested information or error status. There is no session notion in OT Rainbow system, so requests could be issued according stateless model, without transport conservation between them. Additional data could be provided in message body. JSON is used as a main format for data encoding in message body part. Each request is started with the following pattern /{module}/{version}/ where {module} is a portal module name to address and {version} is a version of used API, par example, “v1.0”.  ### Security considerations  Each request should contain some credential information to authenticate itself. Standard HTTP authentication with basic/bearer modes is used. JSON Web Token mechanism is used to provide authentication information. JWT has a expire timeout that is controlled by OT Rainbow portal to prevent very long token usage. Also authentication with application token is used. The token must be provided in the request HTTP header, using a custom header: APIKey. At server side, token is verified, and if it doesn’t match, 403 Not Allowed response is sent. TLS is used as a transport protocol to support message exchanges between OT Rainbow portal and an application.  
 *
 * OpenAPI spec version: 1.84.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RainbowEnduserPortal) {
      root.RainbowEnduserPortal = {};
    }
    root.RainbowEnduserPortal.SendJoinConferenceInvitationEmail = factory(root.RainbowEnduserPortal.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The SendJoinConferenceInvitationEmail model module.
   * @module model/SendJoinConferenceInvitationEmail
   * @version 1.84.0
   */

  /**
   * Constructs a new <code>SendJoinConferenceInvitationEmail</code>.
   * @alias module:model/SendJoinConferenceInvitationEmail
   * @class
   * @param users {Array.<String>} A list of rainbow userId
   * @param emails {Array.<String>} A list of guest user. Persons don't have a Rainbow account.
   */
  var exports = function(users, emails) {
    var _this = this;

    _this['users'] = users;
    _this['emails'] = emails;
  };

  /**
   * Constructs a <code>SendJoinConferenceInvitationEmail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendJoinConferenceInvitationEmail} obj Optional instance to populate.
   * @return {module:model/SendJoinConferenceInvitationEmail} The populated <code>SendJoinConferenceInvitationEmail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('users')) {
        obj['users'] = ApiClient.convertToType(data['users'], ['String']);
      }
      if (data.hasOwnProperty('emails')) {
        obj['emails'] = ApiClient.convertToType(data['emails'], ['String']);
      }
      if (data.hasOwnProperty('lang')) {
        obj['lang'] = ApiClient.convertToType(data['lang'], 'String');
      }
      if (data.hasOwnProperty('instantMessage')) {
        obj['instantMessage'] = ApiClient.convertToType(data['instantMessage'], 'String');
      }
    }
    return obj;
  }

  /**
   * A list of rainbow userId
   * @member {Array.<String>} users
   */
  exports.prototype['users'] = undefined;
  /**
   * A list of guest user. Persons don't have a Rainbow account.
   * @member {Array.<String>} emails
   */
  exports.prototype['emails'] = undefined;
  /**
   * Language of the email notification if user language value is not available.
   * @member {String} lang
   * @default 'en'
   */
  exports.prototype['lang'] = 'en';
  /**
   * When the meeting is an instant meeting nor a scheduled meeting, free message reported to a mail and to an instant message.    In addition with an email, a message stanza is sent to each rainbow users. This allow clients to be notified and join the room, then join the conference:        ```html <message           from='inviter user's jid'           to='invited user's jid '>            <x xmlns='jabber:x:audioconference'                 jid: 'room jid'                 message: 'instantMessage given in body parameter' MAY BE NULL as data is not mandatory                 confendpointid: 'confId'/>    </message> ``` 
   * @member {String} instantMessage
   */
  exports.prototype['instantMessage'] = undefined;



  return exports;
}));


